services:
  jenkins:
    container_name: globomantics-jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./jenkins_home:/var/jenkins_home",,
